### PR TITLE
Made exception messages more descriptive for cases when test suites or flows are incorrectly disposed

### PR DESCRIPTION
**Pull request by boris-yakhno**

### CODE REVIEW

**Comment by boris-yakhno** [comment]
Hello @matt-richardson,

Could you please take a look at this PR and check that the changes in TeamCityTestSuiteBlock.cs will help with diagnosing the problem you described in https://github.com/JetBrains/TeamCity.ServiceMessages/pull/34?

**Comment by matt-richardson** [comment]
> Hello @matt-richardson,
> 
> Could you please take a look at this PR and check that the changes in TeamCityTestSuiteBlock.cs will help with diagnosing the problem you described in #34?

Apologies @boris-yakhno, juggling too many things lately and didn't get a chance to test it. I'll pull it in and let you know how it goes.

**Comment by boris-yakhno** [comment]
@matt-richardson No problem. I've already merged that PR into master and released a new nuget package with the changes. If that doesn't solve your issues or you see room for improvement please don't hesitate to open a new issue or a PR.

**Comment by matt-richardson** [comment]
Hi @boris-yakhno 

I haven't investigated very far yet, but one pulling this in, I got this exception:

```
  Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> System.TypeInitializationException: The type initializer for 'TeamCity.VSTest.TestLogger.TeamCityTestLogger' threw an exception.
   ---> System.MissingMethodException: Method not found: 'JetBrains.TeamCity.ServiceMessages.Write.Special.ITeamCityWriter JetBrains.TeamCity.ServiceMessages.Write.Special.ITeamCityServiceMessages.CreateWriter(System.Action`1<System.String>)'.
     at TeamCity.VSTest.TestLogger.IoCConfiguration.Apply(IMutableContainer container)+MoveNext()
     at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
     at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
     at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at TeamCity.VSTest.TestLogger.TeamCityTestLogger..cctor()
     --- End of inner exception stack trace ---
     at TeamCity.VSTest.TestLogger.TeamCityTestLogger..ctor()
     at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
     --- End of inner exception stack trace ---
     at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
     at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
     at System.Activator.CreateInstance(Type type)
     at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginManager.CreateTestExtension[T](Type extensionType)
     at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.Utilities.LazyExtension`2.get_Value()
     at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.TestLoggerManager.InitializeLoggerByUri(Uri uri, Dictionary`2 parameters)
     at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.TestLoggerManager.Initialize(String runSettings)
     at Microsoft.VisualStudio.TestPlatform.Client.TestPlatform.CreateTestRunRequest(IRequestData requestData, TestRunCriteria testRunCriteria, TestPlatformOptions options, Dictionary`2 sourceToSourceDetailMap, IWarningLogger warningLogger)
     at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(IRequestData requestData, TestRunCriteria testRunCriteria, ITestRunEventsRegistrar testRunEventsRegistrar, TestPlatformOptions options, Dictionary`2 sourceToSourceDetailMap)
     at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(TestRunRequestPayload testRunRequestPayload, ITestHostLauncher3 testHostLauncher, ITestRunEventsRegistrar testRunEventsRegistrar, ProtocolConfig protocolConfig)
     at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumentExecutor.RunTests(String runSettings)
     at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumentExecutor.Execute()
     at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.ExecuteArgumentProcessor(IArgumentProcessor processor, Int32& exitCode)
     at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.Execute(String[] args)
     at Microsoft.VisualStudio.TestPlatform.CommandLine.Program.Run(String[] args, UiLanguageOverride uiLanguageOverride)
     at Microsoft.VisualStudio.TestPlatform.CommandLine.Program.Main(String[] args)
```

Did this break compatibility in some way?

**Comment by boris-yakhno** [comment]
Hi @matt-richardson,

backwards compatibility was broken in TeamCity.ServiceMessages version 4.0.0. That was an oversight on my part, thank you for bringing my attention to it.
You can either upgrade TeamCity.VSTest.TestLogger / TestAdapter to version [1.0.37](https://www.nuget.org/packages/TeamCity.VSTest.TestAdapter/1.0.37) (it is compatible with TeamCity.ServiceMessages 4.x), or you can wait a couple of days for me to fix the backwards compatibility in TeamCity.ServiceMessages.

However, from the stacktrace in #34 I thought that you were using TeamCity.ServiceMessages separately from TeamCity.VSTest.TestLogger, or was I mistaken? Could you please briefly describe your use cases so we're on the same page?

**Comment by matt-richardson** [comment]
> However, from the stacktrace in https://github.com/JetBrains/TeamCity.ServiceMessages/pull/34 I thought that you were using TeamCity.ServiceMessages separately from TeamCity.VSTest.TestLogger, or was I mistaken? Could you please briefly describe your use cases so we're on the same page?

We are using both :)

We are using the TeamCity.ServiceMessages from within our code for a custom test runner we have.

We are also using xunit for other tests, and using the `TeamCity.VSTest.TestLogger` to emit those tests to TeamCity.

**Comment by boris-yakhno** [comment]
Hello @matt-richardson,
Thank you for the explanation!
Could you please describe your setup in more detail? Do you reference `TeamCity.ServiceMessages` and `TeamCity.VSTest.TestLogger` through nuget packages, or do you use explicit references to dlls in your projects? I'm not sure how you're getting the error above. I can only expect it to happen when `TeamCity.ServiceMessages.dll` is updated manually without updating `TeamCity.VSTest.TestLogger.dll` and I don't quite understand the use case for that.

**Pull request merged**
