### PR TITLE
Do not reset the flowId / timestamp key if it is already set.

### LINKED ISSUE #29: FlowMessageUpdater resets the flowId, even if it has already been set
We are using the standard ".NET CLI (dotnet)" build runner from TeamCity 2018.2.1, which automatically loads [teamcity-msbuild-logger](https://github.com/JetBrains/teamcity-msbuild-logger).

In our build process, we send prepared TeamCity service messages containing the already generated flowId / parent keys (for correctly displaying nested blocks and messages from parallel threads).
The problem is that when processing raw messages, FlowMessageUpdater is called, which **resets our flowId values**.
This breaks our the parent-child relationship of the blocks.

A similar problem with TimestampUpdater. It also changes our timestamp values, but it's not so critical.

To solve this problem, it’s enough not to change the flowId / timestamp values if they are already in the message.

### PR DESCRIPTION
**Pull request by AlexanderKholodov46**
Fixes #29

### CODE REVIEW

**Comment by AlexanderKholodov46** [comment]
Hi guys
What news?

**Comment by NikolayPianikov** [comment]
@AlexanderKholodov46 I suggested a performance improvement in my comments, could you find a time to look into it?

**Comment by AlexanderKholodov46** [comment]
@NikolayPianikov I'm sorry, but I don’t see your comments about performance improvement. Could you please clarify?

**Comment by NikolayPianikov** [comment]
@AlexanderKholodov46 It's my fault, I did not press `Submit` for review

**Comment by NikolayPianikov** [comment]
Looks good and thanks for contribution!

**Comment by NikolayPianikov** [comment]
@AlexanderKholodov46 Do you suppose to get a nuget package with this fix ASAP? What is your usage scenario?

**Comment by AlexanderKholodov46** [comment]
> @AlexanderKholodov46 Do you suppose to get a nuget package with this fix ASAP? What is your usage scenario?

Thanks! We would like to receive this patch as part of the standard bundled [teamcity-dotnet-plugin](https://github.com/JetBrains/teamcity-dotnet-plugin) in the next planned release. As a dirty hack, we already use our version of this plugin - there is no need for speed.

**Pull request merged**
